version: '3.4'

services:
  sveltekit-appwrite:
    image: sveltekit-appwrite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
